name: calculate-PI-squared

on:
  workflow_dispatch:

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run calculate-PI-squared.py
      run: python calculate-PI-squared.py
