name: Test-1-calculate-Riemann-zeta-function

on:
  workflow_dispatch:
    inputs:
      n:
        description: '확인 및 계산할 자연수의 개수'
        required: false
        default: '10'
        type: string

run-name: Test-1-calculate-Riemann-zeta-function [ ${{ github.event.inputs.n || '10' }} ]

concurrency:
  group: my-workflow-group

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Run calculate.py
      run: python calculate.py ${{ github.event.inputs.n || '10' }}
